#!/usr/bin/env python3
"""Generate the Worker domain-policy tables from the retained Python runtime."""

from __future__ import annotations

import hashlib
import json
import stringprep
from pathlib import Path
from unicodedata import ucd_3_2_0

import tldextract


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "generated" / "domain-policy-data.js"
MAX_CODE_POINT = 0x110000


def scalar_values():
    return (
        value
        for value in range(MAX_CODE_POINT)
        if not 0xD800 <= value <= 0xDFFF
    )


def ranges(predicate) -> list[list[int]]:
    result: list[list[int]] = []
    start: int | None = None
    previous: int | None = None
    for value in scalar_values():
        if predicate(chr(value)):
            if start is None:
                start = previous = value
            elif previous is not None and value == previous + 1:
                previous = value
            else:
                assert previous is not None
                result.append([start, previous])
                start = previous = value
        elif start is not None:
            assert previous is not None
            result.append([start, previous])
            start = previous = None
    if start is not None:
        assert previous is not None
        result.append([start, previous])
    return result


def mappings(function) -> list[list[object]]:
    result: list[list[object]] = []
    for value in scalar_values():
        character = chr(value)
        mapped = function(character)
        if mapped != character:
            result.append([value, mapped])
    return result


def prohibited(character: str) -> bool:
    return any(
        predicate(character)
        for predicate in (
            stringprep.in_table_c12,
            stringprep.in_table_c22,
            stringprep.in_table_c3,
            stringprep.in_table_c4,
            stringprep.in_table_c5,
            stringprep.in_table_c6,
            stringprep.in_table_c7,
            stringprep.in_table_c8,
            stringprep.in_table_c9,
        )
    )


def snapshot_path() -> Path:
    root = Path(tldextract.__file__).resolve().parent
    path = root / ".tld_set_snapshot"
    if not path.is_file():
        raise FileNotFoundError(f"tldextract snapshot is unavailable: {path}")
    return path


def psl_rules(path: Path) -> tuple[list[str], list[str], list[str]]:
    exact: set[str] = set()
    wildcard: set[str] = set()
    exception: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        rule = raw.strip()
        if not rule or rule.startswith("//"):
            continue
        target = exact
        if rule.startswith("! "):
            raise ValueError(f"invalid PSL exception rule: {rule}")
        if rule.startswith("!"):
            target = exception
            rule = rule[1:]
        elif rule.startswith("*."):
            target = wildcard
            rule = rule[2:]
        target.add(rule.lower().encode("idna").decode("ascii"))
    return sorted(exact), sorted(wildcard), sorted(exception)


def export(name: str, value: object) -> str:
    return f"export const {name} = {json.dumps(value, ensure_ascii=False, separators=(',', ':'))};\n"


def main() -> None:
    snapshot = snapshot_path()
    exact, wildcard, exception = psl_rules(snapshot)
    digest = hashlib.sha256(snapshot.read_bytes()).hexdigest()
    content = [
        "// Generated by scripts/generate-domain-policy.py. Do not edit.\n",
        export("PSL_SHA256", digest),
        export("PSL_EXACT_RULES", exact),
        export("PSL_WILDCARD_RULES", wildcard),
        export("PSL_EXCEPTION_RULES", exception),
        export("PYTHON_WHITESPACE_RANGES", ranges(str.isspace)),
        export("PYTHON_LOWER_MAP", mappings(str.lower)),
        export("NAMEPREP_B1_RANGES", ranges(stringprep.in_table_b1)),
        export("NAMEPREP_B2_MAP", mappings(stringprep.map_table_b2)),
        export("NAMEPREP_PROHIBITED_RANGES", ranges(prohibited)),
        export("NAMEPREP_RANDAL_RANGES", ranges(stringprep.in_table_d1)),
        export("NAMEPREP_LCAT_RANGES", ranges(stringprep.in_table_d2)),
        export(
            "UNICODE_3_2_UNASSIGNED_RANGES",
            ranges(lambda character: ucd_3_2_0.category(character) == "Cn"),
        ),
    ]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("".join(content), encoding="utf-8")
    print(
        json.dumps(
            {
                "output": str(OUTPUT),
                "psl_sha256": digest,
                "exact_rules": len(exact),
                "wildcard_rules": len(wildcard),
                "exception_rules": len(exception),
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
