FROM node:22-alpine

WORKDIR /app
COPY index-worker/src /app/index-worker/src
COPY czds-worker/src /app/czds-worker/src
COPY czds-worker/container /app/czds-worker/container
COPY czds-worker/package.json /app/czds-worker/package.json

CMD ["node", "/app/czds-worker/container/server.js"]
